function GetHeroChoices() {
    return [
        { name: "Golem", id: 0 },
        { name: "Warforged Giant", id: 0 },
        { name: "Ogre chieftain", id: 0 },
        { name: "Cadaver Collector", id: 0 },
        { name: "Tortle Monk", id: 0 },
        { name: "Vanguard", id: 0 },
        { name: "Crusader", id: 0 },
        { name: "Berserker", id: 0 },
        { name: "War Priest", id: 0 },
        { name: "Centurion", id: 0 },
        { name: "Sacred Bladesman", id: 0 },
        { name: "Eldritch knight", id: 0 },
        { name: "Spartan", id: 0 },
        { name: "Ninja", id: 0 },
        { name: "Hitman", id: 0 },
        { name: "Jester", id: 0 },
        { name: "Trophy Hunter", id: 0 },
        { name: "Necromancer", id: 0 },
        { name: "Lich", id: 0 },
        { name: "Invader", id: 0 },
        { name: "Sorceress", id: 0 },
        { name: "Elemental Druid", id: 0 },
        { name: "Bandit King", id: 0 },
        { name: "Gunslinger", id: 0 },
        { name: "Crossbowman", id: 0 },
        { name: "Forest Ranger", id: 0 },
        { name: "Cleric", id: 0 },
        { name: "Bard", id: 0 },
        { name: "Demon Hunter", id: 0 },
        { name: "Revolutionary", id: 0 },
        { name: "Mind Flayer", id: 0 },
        { name: "Sapper", id: 0 },
        { name: "Jailmaster", id: 0 },
    ];
}