function GetHeroChoices() {
    return [
        { name: "Golem", id: 0, abbrev: "GL" },
        { name: "Warforged Giant", id: 0, abbrev: "WG" },
        { name: "Ogre chieftain", id: 0, abbrev: "OC" },
        { name: "Cadaver Collector", id: 0, abbrev: "CC" },
        { name: "Tortle Monk", id: 0, abbrev: "TM" },
        { name: "Vanguard", id: 0, abbrev: "VA"  },
        { name: "Crusader", id: 0, abbrev: "CR"  },
        { name: "Berserker", id: 0, abbrev: "BE"  },
        { name: "War Priest", id: 0, abbrev: "WP"  },
        { name: "Centurion", id: 0, abbrev: "CE"  },
        { name: "Sacred Bladesman", id: 0, abbrev: "SB"  },
        { name: "Eldritch knight", id: 0, abbrev: "EK" },
        { name: "Spartan", id: 0, abbrev: "SP"  },
        { name: "Ninja", id: 0, abbrev: "NJ"  },
        { name: "Hitman", id: 0, abbrev: "HM"  },
        { name: "Jester", id: 0, abbrev: "JE"  },
        { name: "Trophy Hunter", id: 0, abbrev: "TH"  },
        { name: "Necromancer", id: 0, abbrev: "NE"  },
        { name: "Lich", id: 0, abbrev: "LI"  },
        { name: "Invader", id: 0, abbrev: "IV"  },
        { name: "Sorceress", id: 0, abbrev: "SO"  },
        { name: "Elemental Druid", id: 0, abbrev: "ED"  },
        { name: "Bandit King", id: 0, abbrev: "BK"  },
        { name: "Gunslinger", id: 0, abbrev: "GS"  },
        { name: "Crossbowman", id: 0, abbrev: "CB"  },
        { name: "Forest Ranger", id: 0, abbrev: "FR"  },
        { name: "Cleric", id: 0, abbrev: "CL"  },
        { name: "Bard", id: 0, abbrev: "BR"  },
        { name: "Demon Hunter", id: 0, abbrev: "DH"  },
        { name: "Revolutionary", id: 0, abbrev: "RV"  },
        { name: "Mind Flayer", id: 0, abbrev: "MF"  },
        { name: "Sapper", id: 0, abbrev: "SA"  },
        { name: "Jailmaster", id: 0, abbrev: "JM" },
    ];
}